name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: 'stable'
      - name: Set up PATH
        run: |
          echo "${ANDROID_HOME}/build-tools/34.0.0" >> $GITHUB_PATH
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Install packages needed for GLFW
        run: |
          sudo apt install -y libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libgl-dev libxxf86vm-dev
      - name: Build APK
        run: |
          nimble androidPackage -Y
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Animythril
          path: android/build/outputs/apk/debug/android-debug.apk
