name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: 'stable'
      - name: Build APK
        run: |
          nimble androidPackage -Y
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Animythril
          path: android/build/outputs/apk/debug/android-debug.apk
